In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
EU_COUNTRIES = [
    'BE', 'BG', 'CZ', 'DK', 'DE', 'EE', 'IE', 
    'EL', 'ES', 'FR', 'HR', 'IT', 'CY', 'LV',
    'LT', 'LU', 'HU', 'MT', 'NL', 'AT', 'PL', 
    'PT', 'RO', 'SI', 'SK', 'FI', 'SE'
]

EFTA_COUNTRIES = ['IS', 'LI', 'NO', 'CH']

EU_EFTA = EU_COUNTRIES + EFTA_COUNTRIES

### AI adoption rate (2021, 2023, 2024)

The dependent variable AI adoption rate is the proportion of firms (percent) withing each country - sector using at least one type of AI. Take it as it is.

In [20]:
path = 'C:/Users/ydmar/Documents/UW/Master thesis/Step 1 - meeting 18.10/data - september/'

ain2 = pd.read_csv(path + 'estat_isoc_eb_ain2.tsv/estat_isoc_eb_ain2.tsv', sep='\t')
print(ain2)

       freq,size_emp,nace_r2,indic_is,unit,geo\TIME_PERIOD 2021    2023  2024
0                      A,GE10,C,E_AIX_CC1SIX_DA,PC_ENT,AT     :    8.24     :
1                      A,GE10,C,E_AIX_CC1SIX_DA,PC_ENT,BA     :   17.89     :
2                      A,GE10,C,E_AIX_CC1SIX_DA,PC_ENT,BE     :   21.08     :
3                      A,GE10,C,E_AIX_CC1SIX_DA,PC_ENT,BG     :   13.97     :
4                      A,GE10,C,E_AIX_CC1SIX_DA,PC_ENT,CY     :    9.89     :
...                                                   ...    ...     ...   ...
221987            A,GE10,S951,E_DI3_VLO_AI_TANY,PC_ENT,RO     :       0     :
221988            A,GE10,S951,E_DI3_VLO_AI_TANY,PC_ENT,RS     :       0     :
221989            A,GE10,S951,E_DI3_VLO_AI_TANY,PC_ENT,SE     :       0     :
221990            A,GE10,S951,E_DI3_VLO_AI_TANY,PC_ENT,SI     :       0     :
221991            A,GE10,S951,E_DI3_VLO_AI_TANY,PC_ENT,SK     :       0     :

[221992 rows x 4 columns]

In [ ]:
ain2_split = ain2[r'freq,size_emp,nace_r2,indic_is,unit,geo\TIME_PERIO'].str.split(',', expand=True)
ain2 = pd.concat([ain2, ain2_split], axis=1)
ain2.rename(columns={0: 'freq', 1: 'size_emp', 2: 'nace_r2',  3: 'indic_is', 4: 'unit', 5: 'geo_TIME_PERIOD'}, inplace=True)
ain2 = ain2.drop(r'freq,size_emp,nace_r2,indic_is,unit,geo\TIME_PERIOD', axis=1)
ain2.rename(columns={"geo_TIME_PERIOD": "geo"}, inplace=True)
ain2.columns = ain2.columns.str.strip()
ain2.info()

In [30]:
years_take = ['2021', '2023', '2024']

pattern = re.compile(r'^\s*(\d+(?:\.\d+)?)?\s*[: ]*\s*([A-Za-z]+)?\s*$')

for year in years_take:
    column_series = ain2[year].astype(str).str.strip() 

    extracted_df = column_series.str.extract(pattern, expand=True)
    # print(extracted_df)

    num_col_name = f'num_{year}'
    ain2[num_col_name] = pd.to_numeric(extracted_df[0], errors='coerce') 
    # print(ain2[num_col_name])
    
    flag_col_name = f'flag_{year}'
    ain2[flag_col_name] = extracted_df[1].fillna('NaN') 
    # print(ain2[flag_col_name])
    # print('#########################')
# Display the resulting DataFrame
print(ain2)

       2021    2023 2024 freq size_emp nace_r2           indic_is    unit geo  \
0        :    8.24    :     A     GE10       C    E_AIX_CC1SIX_DA  PC_ENT  AT
1        :   17.89    :     A     GE10       C    E_AIX_CC1SIX_DA  PC_ENT  BA
2        :   21.08    :     A     GE10       C    E_AIX_CC1SIX_DA  PC_ENT  BE
3        :   13.97    :     A     GE10       C    E_AIX_CC1SIX_DA  PC_ENT  BG
4        :    9.89    :     A     GE10       C    E_AIX_CC1SIX_DA  PC_ENT  CY
...     ...     ...  ...  ...      ...     ...                ...     ...  ..
221987   :       0    :     A     GE10    S951  E_DI3_VLO_AI_TANY  PC_ENT  RO
221988   :       0    :     A     GE10    S951  E_DI3_VLO_AI_TANY  PC_ENT  RS
221989   :       0    :     A     GE10    S951  E_DI3_VLO_AI_TANY  PC_ENT  SE
221990   :       0    :     A     GE10    S951  E_DI3_VLO_AI_TANY  PC_ENT  SI
221991   :       0    :     A     GE10    S951  E_DI3_VLO_AI_TANY  PC_ENT  SK

        num_2021 flag_2021  num_2023 flag_2023  num_2024 flag_2024
0            NaN       NaN      8.24       NaN       NaN       NaN
1            NaN       NaN     17.89       NaN       NaN       NaN
2            NaN       NaN     21.08       NaN       NaN       NaN
3            NaN       NaN     13.97       NaN       NaN       NaN
4            NaN       NaN      9.89       NaN       NaN       NaN
...          ...       ...       ...       ...       ...       ...
221987       NaN       NaN      0.00       NaN       NaN       NaN
221988       NaN       NaN      0.00       NaN       NaN       NaN
221989       NaN       NaN      0.00       NaN       NaN       NaN
221990       NaN       NaN      0.00       NaN       NaN       NaN
221991       NaN       NaN      0.00       NaN       NaN       NaN

[221992 rows x 15 columns]

In [31]:
ain2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221992 entries, 0 to 221991
Data columns (total 15 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   2021       221992 non-null  object
 1   2023       221992 non-null  object
 2   2024       221992 non-null  object
 3   freq       221992 non-null  object
 4   size_emp   221992 non-null  object
 5   nace_r2    221992 non-null  object
 6   indic_is   221992 non-null  object
 7   unit       221992 non-null  object
 8   geo        221992 non-null  object
 9   num_2021   105362 non-null  float64
 10  flag_2021  221992 non-null  object
 11  num_2023   156020 non-null  float64
 12  flag_2023  221992 non-null  object
 13  num_2024   132088 non-null  float64
 14  flag_2024  221992 non-null  object
dtypes: float64(3), object(12)
memory usage: 25.4+ MB

In [32]:
ain2.drop(['2021', '2023', '2024'], axis='columns', inplace=True)

In [ ]:
ain2.describe()

            num_2021       num_2023       num_2024
count  105362.000000  156020.000000  132088.000000
mean       10.868867      14.625982      14.061412
std        20.984997      22.858054      20.959793
min         0.000000       0.000000       0.000000
25%         0.520000       1.210000       1.730000
50%         2.430000       4.000000       5.240000
75%         8.330000      16.290000      16.090000
max       100.000000     100.000000     100.000000

In [35]:
ain2.describe(include=["object", "bool"])

,freq,size_emp,nace_r2,indic_is,unit,geo,flag_2021,flag_2023,flag_2024
count,221992,221992,221992,221992,221992,221992,221992,221992,221992
unique,1,1,48,62,6,36,2,4,4
top,A,GE10,C-E,E_AI_BCDP,PC_ENT,PL,NaN,NaN,NaN
freq,221992,221992,4717,5125,88814,7716,209595,194904,205091

In [ ]:
ain2.to_csv('ain2.csv', index = False)

### Wages and Labour cost from LC survey (2016, 2020)

In [36]:
path = 'C:/Users/ydmar/Documents/UW/Master thesis/Step 1 - meeting 18.10/data - september/'

wg = pd.read_csv(path + 'estat_lc_ncost_r2.tsv/estat_lc_ncost_r2.tsv', sep='\t')
print(wg)

        freq,currency,unit,sizeclas,nace_r2,lcstruct,geo\TIME_PERIOD  \
0                             A,EUR,P_SAL_H,10-49,B,D01,AL
1                             A,EUR,P_SAL_H,10-49,B,D01,AT
2                             A,EUR,P_SAL_H,10-49,B,D01,BA
3                             A,EUR,P_SAL_H,10-49,B,D01,BE
4                             A,EUR,P_SAL_H,10-49,B,D01,BG
...                                                    ...
1254268                     A,PPS,TOTAL,TOTAL,S96,D1111,RS
1254269                     A,PPS,TOTAL,TOTAL,S96,D1111,SI
1254270                     A,PPS,TOTAL,TOTAL,S96,D1111,SK
1254271                     A,PPS,TOTAL,TOTAL,S96,D1111,TR
1254272                     A,PPS,TOTAL,TOTAL,S96,D1111,UK

               2008         2012         2016        2020
0                 :         1.64         2.50        4.28
1             22.37        27.20        30.99       33.00
2                 :         3.71         3.91        4.94
3               : @C       36.34        35.48       34.67
4              2.53         3.42          : @C       5.87
...              ...          ...          ...         ...
1254268           :            :    31340162 d  32751700 d
1254269   47753817 d           :    41270850 d  43110845 d
1254270   34403143 d   35211330 d    33838580    36812309
1254271           :            :    490463146   542511304
1254272  5974985906   4267800190   4946674191           :

[1254273 rows x 5 columns]

In [ ]:
wg_split = wg[r'freq,currency,unit,sizeclas,nace_r2,lcstruct,geo\TIME_PERIOD'].str.split(',', expand=True)
wg = pd.concat([wg, wg_split], axis=1)
wg.rename(columns={0: 'freq', 1: 'currency', 2: 'unit',  3: 'sizeclas', 4: 'nace_r2', 5: 'lcstruct', 6:  'geo_TIME_PERIOD'}, inplace=True)
wg = wg.drop(r'freq,currency,unit,sizeclas,nace_r2,lcstruct,geo\TIME_PERIOD', axis=1)
wg.rename(columns={"geo_TIME_PERIOD": "geo"}, inplace=True)
wg.columns = wg.columns.str.strip()
wg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1254273 entries, 0 to 1254272
Data columns (total 11 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   2008      1254273 non-null  object
 1   2012      1254273 non-null  object
 2   2016      1254273 non-null  object
 3   2020      1254273 non-null  object
 4   freq      1254273 non-null  object
 5   currency  1254273 non-null  object
 6   unit      1254273 non-null  object
 7   sizeclas  1254273 non-null  object
 8   nace_r2   1254273 non-null  object
 9   lcstruct  1254273 non-null  object
 10  geo       1254273 non-null  object
dtypes: object(11)
memory usage: 105.3+ MB

In [ ]:
years_take = ['2016', '2020']
data_temp  = wg.copy()

pattern = re.compile(r'^\s*(\d+(?:\.\d+)?)?\s*[: ]*\s*([A-Za-z]+)?\s*$')

for year in years_take:
    column_series = data_temp[year].astype(str).str.strip() 

    extracted_df = column_series.str.extract(pattern, expand=True)
    # print(extracted_df)

    num_col_name = f'num_{year}'
    data_temp[num_col_name] = pd.to_numeric(extracted_df[0], errors='coerce') 
    # print(ain2[num_col_name])
    
    flag_col_name = f'flag_{year}'
    data_temp[flag_col_name] = extracted_df[1].fillna('NaN') 
    # print(ain2[flag_col_name])
    # print('#########################')
# Display the resulting DataFrame
wg_new = data_temp
print(wg_new)

                2008         2012         2016        2020 freq currency  \
0                 :         1.64         2.50        4.28     A      EUR
1             22.37        27.20        30.99       33.00     A      EUR
2                 :         3.71         3.91        4.94     A      EUR
3               : @C       36.34        35.48       34.67     A      EUR
4              2.53         3.42          : @C       5.87     A      EUR
...              ...          ...          ...         ...  ...      ...
1254268           :            :    31340162 d  32751700 d    A      PPS
1254269   47753817 d           :    41270850 d  43110845 d    A      PPS
1254270   34403143 d   35211330 d    33838580    36812309     A      PPS
1254271           :            :    490463146   542511304     A      PPS
1254272  5974985906   4267800190   4946674191           :     A      PPS

            unit sizeclas nace_r2 lcstruct geo      num_2016 flag_2016  \
0        P_SAL_H    10-49       B      D01  AL  2.500000e+00       NaN
1        P_SAL_H    10-49       B      D01  AT  3.099000e+01       NaN
2        P_SAL_H    10-49       B      D01  BA  3.910000e+00       NaN
3        P_SAL_H    10-49       B      D01  BE  3.548000e+01       NaN
4        P_SAL_H    10-49       B      D01  BG           NaN       NaN
...          ...      ...     ...      ...  ..           ...       ...
1254268    TOTAL    TOTAL     S96    D1111  RS  3.134016e+07         d
1254269    TOTAL    TOTAL     S96    D1111  SI  4.127085e+07         d
1254270    TOTAL    TOTAL     S96    D1111  SK  3.383858e+07       NaN
1254271    TOTAL    TOTAL     S96    D1111  TR  4.904631e+08       NaN
1254272    TOTAL    TOTAL     S96    D1111  UK  4.946674e+09       NaN

             num_2020 flag_2020
0        4.280000e+00       NaN
1        3.300000e+01       NaN
2        4.940000e+00       NaN
3        3.467000e+01       NaN
4        5.870000e+00       NaN
...               ...       ...
1254268  3.275170e+07         d
1254269  4.311084e+07         d
1254270  3.681231e+07       NaN
1254271  5.425113e+08       NaN
1254272           NaN       NaN

[1254273 rows x 15 columns]

In [ ]:
wg_new.drop(['2008', '2012','2016', '2020'], axis='columns', inplace=True)
wg_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1254273 entries, 0 to 1254272
Data columns (total 11 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   freq       1254273 non-null  object
 1   currency   1254273 non-null  object
 2   unit       1254273 non-null  object
 3   sizeclas   1254273 non-null  object
 4   nace_r2    1254273 non-null  object
 5   lcstruct   1254273 non-null  object
 6   geo        1254273 non-null  object
 7   num_2016   837744 non-null   float64
 8   flag_2016  1254273 non-null  object
 9   num_2020   764253 non-null   float64
 10  flag_2020  1254273 non-null  object
dtypes: float64(2), object(9)
memory usage: 105.3+ MB

In [41]:
wg_new.describe()

           num_2016      num_2020
count  8.377440e+05  7.642530e+05
mean   5.350333e+09  5.503536e+09
std    8.032602e+10  9.636738e+10
min    1.100000e-01  1.000000e+00
25%    4.620000e+02  6.220000e+02
50%    8.892000e+03  1.099200e+04
75%    1.584898e+06  2.209709e+06
max    1.262843e+13  1.710201e+13

In [42]:
wg_new.describe(include=["object", "bool"])

,2016,2020,freq,currency,unit,sizeclas,nace_r2,lcstruct,geo,flag_2016,flag_2020
count,1254273,1254273,1254273,1254273,1254273,1254273,1254273,1254273,1254273,1254273,1254273
unique,284120,265191,1,3,4,8,114,3,47,4,4
top,:,:,A,PPS,TOTAL,GE10,B-E,D01,EA16,NaN,NaN
freq,193731,281379,1254273,429552,330018,183378,12528,418250,32076,1141008,1163772

In [45]:
wg_new.to_csv('lc.csv', index = False)

### Concentration is the share of firms that have more than 250 employees

Possible dat from the 2005 - 2024. Selected 2016 and 2020.

In [55]:
path = 'C:/Users/ydmar/Documents/UW/Master thesis/Step 1 - meeting 18.10/data - september/'

conctr = pd.read_csv(path + 'estat_sbs_sc_sca_r2.tsv/estat_sbs_sc_sca_r2.tsv', sep='\t')
print(conctr)

       freq,nace_r2,indic_sb,size_emp,geo\TIME_PERIOD 2005  2006  2007  2008   \
0                                   A,B,V11110,0-9,AL    :     :     :     :
1                                   A,B,V11110,0-9,AT    :     :     :   237
2                                   A,B,V11110,0-9,BA    :     :     :     :
3                                   A,B,V11110,0-9,BE    :     :     :   : @C
4                                   A,B,V11110,0-9,BG    :     :     :   199
...                                               ...   ...   ...   ...   ...
483382                          A,S95,V92100,TOTAL,RS    :     :     :     :
483383                          A,S95,V92100,TOTAL,SE    :     :     :     :
483384                          A,S95,V92100,TOTAL,SI    :     :     :     :
483385                          A,S95,V92100,TOTAL,SK    :     :     :     :
483386                          A,S95,V92100,TOTAL,UK    :     :     :     :

       2009  2010   2011   2012   2013   2014   2015   2016   2017   2018   \
0         :     :      :      :      :      :      :      :      :      :
1       244   245    242    238    238    227    230    226    215   192 b
2         :     :   150 p  121 p  118 p  121 p  132 e  129 e  121 b   102
3       248   249    227    160    175    149    167    144    173   118 b
4       230   241    245    252    243    228    240    224    215   211 b
...      ...   ...    ...    ...    ...    ...    ...    ...    ...    ...
483382    :     :      :      :      :      :      :   4.2 p  4.2 p   4.3
483383    :     :      :      :      :      :    1.2    1.2    1.2   1.1 b
483384    :     :      :      :      :      :    1.5    1.5    1.5    1.5
483385    :     :      :      :      :    1.3    1.4    1.4    1.5    1.4
483386    :     :      :      :      :      :    6.1   7.3 b   4.4    5.2

       2019  2020
0       502   510
1       183   197
2       101    98
3       140   141
4       190   199
...      ...   ...
483382  4.4   4.7
483383  1.1   1.0
483384  1.5   1.4
483385  1.5   1.4
483386    :     :

[483387 rows x 17 columns]

In [56]:
conctr_split = conctr[r'freq,nace_r2,indic_sb,size_emp,geo\TIME_PERIOD'].str.split(',', expand=True)
conctr = pd.concat([conctr, conctr_split], axis=1)
conctr.rename(columns={0: 'freq', 1: 'nace_r2', 2: 'indic_sb',  3: 'size_emp', 4: 'geo_TIME_PERIOD'}, inplace=True)
conctr = conctr.drop(r'freq,nace_r2,indic_sb,size_emp,geo\TIME_PERIOD', axis=1)
conctr.rename(columns={"geo_TIME_PERIOD": "geo"}, inplace=True)
conctr.columns = conctr.columns.str.strip()
conctr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483387 entries, 0 to 483386
Data columns (total 21 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   2005      483387 non-null  object
 1   2006      483387 non-null  object
 2   2007      483387 non-null  object
 3   2008      483387 non-null  object
 4   2009      483387 non-null  object
 5   2010      483387 non-null  object
 6   2011      483387 non-null  object
 7   2012      483387 non-null  object
 8   2013      483387 non-null  object
 9   2014      483387 non-null  object
 10  2015      483387 non-null  object
 11  2016      483387 non-null  object
 12  2017      483387 non-null  object
 13  2018      483387 non-null  object
 14  2019      483387 non-null  object
 15  2020      483387 non-null  object
 16  freq      483387 non-null  object
 17  nace_r2   483387 non-null  object
 18  indic_sb  483387 non-null  object
 19  size_emp  483387 non-null  object
 20  geo       483387 non-null  object
dtypes: object(21)
memory usage: 77.4+ MB

In [57]:
years_take = ['2016', '2020']
data_temp  = conctr.copy()

pattern = re.compile(r'^\s*(\d+(?:\.\d+)?)?\s*[: ]*\s*([A-Za-z]+)?\s*$')

for year in years_take:
    column_series = data_temp[year].astype(str).str.strip() 

    extracted_df = column_series.str.extract(pattern, expand=True)
    # print(extracted_df)

    num_col_name = f'num_{year}'
    data_temp[num_col_name] = pd.to_numeric(extracted_df[0], errors='coerce') 
    # print(ain2[num_col_name])
    
    flag_col_name = f'flag_{year}'
    data_temp[flag_col_name] = extracted_df[1].fillna('NaN') 
    # print(ain2[flag_col_name])
    # print('#########################')
# Display the resulting DataFrame
conctr_new = data_temp
print(conctr_new)

       2005 2006 2007  2008  2009  2010   2011   2012   2013   2014  ...  \
0        :    :    :     :     :     :      :      :      :      :   ...
1        :    :    :   237   244   245    242    238    238    227   ...
2        :    :    :     :     :     :   150 p  121 p  118 p  121 p  ...
3        :    :    :   : @C  248   249    227    160    175    149   ...
4        :    :    :   199   230   241    245    252    243    228   ...
...     ...  ...  ...   ...   ...   ...    ...    ...    ...    ...  ...
483382   :    :    :     :     :     :      :      :      :      :   ...
483383   :    :    :     :     :     :      :      :      :      :   ...
483384   :    :    :     :     :     :      :      :      :      :   ...
483385   :    :    :     :     :     :      :      :      :    1.3   ...
483386   :    :    :     :     :     :      :      :      :      :   ...

        2020 freq nace_r2 indic_sb size_emp geo num_2016 flag_2016 num_2020  \
0       510     A       B   V11110      0-9  AL      NaN       NaN    510.0
1       197     A       B   V11110      0-9  AT    226.0       NaN    197.0
2        98     A       B   V11110      0-9  BA    129.0         e     98.0
3       141     A       B   V11110      0-9  BE    144.0       NaN    141.0
4       199     A       B   V11110      0-9  BG    224.0       NaN    199.0
...      ...  ...     ...      ...      ...  ..      ...       ...      ...
483382  4.7     A     S95   V92100    TOTAL  RS      4.2         p      4.7
483383  1.0     A     S95   V92100    TOTAL  SE      1.2       NaN      1.0
483384  1.4     A     S95   V92100    TOTAL  SI      1.5       NaN      1.4
483385  1.4     A     S95   V92100    TOTAL  SK      1.4       NaN      1.4
483386    :     A     S95   V92100    TOTAL  UK      7.3         b      NaN

       flag_2020
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
...          ...
483382       NaN
483383       NaN
483384       NaN
483385       NaN
483386       NaN

[483387 rows x 25 columns]

In [58]:
y = 2005
while y <= 2020:
    column_to_drop = str(y)
    conctr_new.drop([column_to_drop], axis='columns', inplace=True)
    y += 1
conctr_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483387 entries, 0 to 483386
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   freq       483387 non-null  object
 1   nace_r2    483387 non-null  object
 2   indic_sb   483387 non-null  object
 3   size_emp   483387 non-null  object
 4   geo        483387 non-null  object
 5   num_2016   221352 non-null  float64
 6   flag_2016  483387 non-null  object
 7   num_2020   214875 non-null  float64
 8   flag_2020  483387 non-null  object
dtypes: float64(2), object(7)
memory usage: 33.2+ MB

In [60]:
conctr_new.to_csv('conctr.csv', index = False)

### Proportion of firms using computer

Possible data from 2009 - 2024. Selected 2016 and 2020.

In [61]:
path = 'C:/Users/ydmar/Documents/UW/Master thesis/Step 1 - meeting 18.10/data - september/'

comp = pd.read_csv(path + 'estat_isoc_ci_cm_pn2.tsv/estat_isoc_ci_cm_pn2.tsv', sep='\t')
print(comp)

     freq,size_emp,nace_r2,indic_is,unit,geo\TIME_PERIOD   2009    2010   \
0                             A,GE10,C,P_CUSE,PC_EMP,AT   51.35   53.31
1                             A,GE10,C,P_CUSE,PC_EMP,BA       :       :
2                             A,GE10,C,P_CUSE,PC_EMP,BE      : u  61.47
3                             A,GE10,C,P_CUSE,PC_EMP,BG    9.58   16.11
4                             A,GE10,C,P_CUSE,PC_EMP,CY   25.17   25.81
...                                                 ...      ...     ...
8815                  A,GE10,S951,P_IUSE,PC_EMP_IACC,SE       :       :
8816                  A,GE10,S951,P_IUSE,PC_EMP_IACC,SI       :       :
8817                  A,GE10,S951,P_IUSE,PC_EMP_IACC,SK       :       :
8818                  A,GE10,S951,P_IUSE,PC_EMP_IACC,TR       :       :
8819                  A,GE10,S951,P_IUSE,PC_EMP_IACC,UK       :       :

       2011     2012     2013     2014     2015    2016    2017    2018   \
0         :    54.27    55.19    56.85        :       :       :       :
1         :        :        :        :        :       :       :   23.54
2     62.10    60.22       : u      : u   56.56   57.93   60.75   59.09
3     16.53    16.39    17.51    18.38    18.38   19.17   18.94   19.76
4     26.27    30.44    28.65    35.56    30.59   32.96   31.70   33.92
...      ...      ...      ...      ...      ...     ...     ...     ...
8815      :    98.35   100.00    97.79   100.00       :       :       :
8816      :   100.00   100.00   100.00   100.00       :       :       :
8817      :    82.88    83.96    74.63   100.00       :       :       :
8818      :        :        :        :    70.61       :       :       :
8819      :    91.30    88.18    93.61    91.41       :       :       :

       2019  2020  2021  2022  2023  2024
0         :     :     :     :     :     :
1     24.60     :     :     :     :     :
2        : u    :     :     :     :     :
3     20.40     :     :     :     :     :
4     31.14     :     :     :     :     :
...      ...   ...   ...   ...   ...   ...
8815      :     :     :     :     :     :
8816      :     :     :     :     :     :
8817      :     :     :     :     :     :
8818      :     :     :     :     :     :
8819      :     :     :     :     :     :

[8820 rows x 17 columns]

In [62]:
comp_split = comp [r'freq,size_emp,nace_r2,indic_is,unit,geo\TIME_PERIOD'].str.split(',', expand=True)
comp = pd.concat([comp, comp_split], axis=1)
comp.rename(columns={0: 'freq', 1: 'size_emp', 2: 'nace_r2',  3: 'indic_is', 4: 'unit', 5: 'geo\TIME_PERIOD'}, inplace=True)
comp  = comp.drop(r'freq,size_emp,nace_r2,indic_is,unit,geo\TIME_PERIOD', axis=1)
comp.rename(columns={"geo_TIME_PERIOD": "geo"}, inplace=True)
comp.columns = comp.columns.str.strip()
comp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8820 entries, 0 to 8819
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   2009             8820 non-null   object
 1   2010             8820 non-null   object
 2   2011             8820 non-null   object
 3   2012             8820 non-null   object
 4   2013             8820 non-null   object
 5   2014             8820 non-null   object
 6   2015             8820 non-null   object
 7   2016             8820 non-null   object
 8   2017             8820 non-null   object
 9   2018             8820 non-null   object
 10  2019             8820 non-null   object
 11  2020             8820 non-null   object
 12  2021             8820 non-null   object
 13  2022             8820 non-null   object
 14  2023             8820 non-null   object
 15  2024             8820 non-null   object
 16  freq             8820 non-null   object
 17  size_emp         8820 non-null   object
 18  nace_r2          8820 non-null   object
 19  indic_is         8820 non-null   object
 20  unit             8820 non-null   object
 21  geo\TIME_PERIOD  8820 non-null   object
dtypes: object(22)
memory usage: 1.5+ MB

<>:3: SyntaxWarning: invalid escape sequence '\T'
<>:3: SyntaxWarning: invalid escape sequence '\T'
C:\Users\ydmar\AppData\Local\Temp\ipykernel_10916\2602886828.py:3: SyntaxWarning: invalid escape sequence '\T'
  comp.rename(columns={0: 'freq', 1: 'size_emp', 2: 'nace_r2',  3: 'indic_is', 4: 'unit', 5: 'geo\TIME_PERIOD'}, inplace=True)

In [63]:
years_take = ['2016', '2020']
data_temp  = comp.copy()

pattern = re.compile(r'^\s*(\d+(?:\.\d+)?)?\s*[: ]*\s*([A-Za-z]+)?\s*$')

for year in years_take:
    column_series = data_temp[year].astype(str).str.strip() 

    extracted_df = column_series.str.extract(pattern, expand=True)
    # print(extracted_df)

    num_col_name = f'num_{year}'
    data_temp[num_col_name] = pd.to_numeric(extracted_df[0], errors='coerce') 
    # print(ain2[num_col_name])
    
    flag_col_name = f'flag_{year}'
    data_temp[flag_col_name] = extracted_df[1].fillna('NaN') 
    # print(ain2[flag_col_name])
    # print('#########################')
# Display the resulting DataFrame
comp_new = data_temp
print(comp_new)

        2009    2010    2011     2012     2013     2014     2015    2016  \
0     51.35   53.31       :    54.27    55.19    56.85        :       :
1         :       :       :        :        :        :        :       :
2        : u  61.47   62.10    60.22       : u      : u   56.56   57.93
3      9.58   16.11   16.53    16.39    17.51    18.38    18.38   19.17
4     25.17   25.81   26.27    30.44    28.65    35.56    30.59   32.96
...      ...     ...     ...      ...      ...      ...      ...     ...
8815      :       :       :    98.35   100.00    97.79   100.00       :
8816      :       :       :   100.00   100.00   100.00   100.00       :
8817      :       :       :    82.88    83.96    74.63   100.00       :
8818      :       :       :        :        :        :    70.61       :
8819      :       :       :    91.30    88.18    93.61    91.41       :

        2017    2018  ... freq size_emp nace_r2 indic_is         unit  \
0         :       :   ...    A     GE10       C   P_CUSE       PC_EMP
1         :   23.54   ...    A     GE10       C   P_CUSE       PC_EMP
2     60.75   59.09   ...    A     GE10       C   P_CUSE       PC_EMP
3     18.94   19.76   ...    A     GE10       C   P_CUSE       PC_EMP
4     31.70   33.92   ...    A     GE10       C   P_CUSE       PC_EMP
...      ...     ...  ...  ...      ...     ...      ...          ...
8815      :       :   ...    A     GE10    S951   P_IUSE  PC_EMP_IACC
8816      :       :   ...    A     GE10    S951   P_IUSE  PC_EMP_IACC
8817      :       :   ...    A     GE10    S951   P_IUSE  PC_EMP_IACC
8818      :       :   ...    A     GE10    S951   P_IUSE  PC_EMP_IACC
8819      :       :   ...    A     GE10    S951   P_IUSE  PC_EMP_IACC

     geo\TIME_PERIOD num_2016 flag_2016 num_2020 flag_2020
0                 AT      NaN       NaN      NaN       NaN
1                 BA      NaN       NaN      NaN       NaN
2                 BE    57.93       NaN      NaN       NaN
3                 BG    19.17       NaN      NaN       NaN
4                 CY    32.96       NaN      NaN       NaN
...              ...      ...       ...      ...       ...
8815              SE      NaN       NaN      NaN       NaN
8816              SI      NaN       NaN      NaN       NaN
8817              SK      NaN       NaN      NaN       NaN
8818              TR      NaN       NaN      NaN       NaN
8819              UK      NaN       NaN      NaN       NaN

[8820 rows x 26 columns]

In [ ]:
y = 2009
while y <= 2024:
    column_to_drop = str(y)
    comp_new.drop([column_to_drop], axis='columns', inplace=True)
    y += 1
comp_new.info()

In [68]:
comp.to_csv('comp.csv', index = False)

### Cost  capital 

is the harmonized bank lending rate on outstanding loans with more than 5 years' maturity; it varies across countries only. Cost of capital gathered in other notebook.

### Energy cost 

is the price of electricity in euros per kilowatt-hour for firms that use between 2 and 20 thousand megawatt-hours per year, including all taxes and fees; it varies across countries only.

In [7]:
path = 'C:/Users/ydmar/Documents/UW/Master thesis/Step 1 - meeting 18.10/data - september/'

enrg_cst = pd.read_csv(path + 'estat_nrg_pc_205.tsv/estat_nrg_pc_205.tsv', sep='\t')
print(enrg_cst)

     freq,product,nrg_cons,unit,tax,currency,geo\TIME_PERIOD 2007-S1   \
0                     S,6000,MWH20-499,KWH,I_TAX,EUR,AL            :
1                     S,6000,MWH20-499,KWH,I_TAX,EUR,AT            :
2                     S,6000,MWH20-499,KWH,I_TAX,EUR,BA            :
3                     S,6000,MWH20-499,KWH,I_TAX,EUR,BE            :
4                     S,6000,MWH20-499,KWH,I_TAX,EUR,BG            :
...                                                 ...           ...
2881                    S,6000,TOT_KWH,KWH,X_VAT,PPS,RS            :
2882                    S,6000,TOT_KWH,KWH,X_VAT,PPS,SE            :
2883                    S,6000,TOT_KWH,KWH,X_VAT,PPS,SI            :
2884                    S,6000,TOT_KWH,KWH,X_VAT,PPS,SK            :
2885                    S,6000,TOT_KWH,KWH,X_VAT,PPS,TR            :

     2007-S2  2008-S1  2008-S2  2009-S1  2009-S2  2010-S1  2010-S2  2011-S1   \
0          :        :        :        :        :        :        :        :
1     0.1412   0.1476    0.144   0.1601   0.1588   0.1545   0.1547   0.1547
2          :        :        :        :        :        :        :        :
3     0.1435   0.1706   0.1728   0.1605   0.1547   0.1562   0.1584   0.1721
4     0.0767   0.0767   0.0874   0.0879   0.0864   0.0854   0.0851   0.0864
...       ...      ...      ...      ...      ...      ...      ...      ...
2881       :        :        :        :        :        :        :        :
2882       :        :        :        :        :        :        :        :
2883       :        :        :        :        :        :        :        :
2884       :        :        :        :        :        :        :        :
2885       :        :        :        :        :        :        :        :

      ...  2020-S2   2021-S1   2021-S2  2022-S1   2022-S2   2023-S1   \
0     ...  0.1243 e  0.1247 e  0.1263 e  0.1268    0.1316   0.1362 e
1     ...   0.1624    0.1683    0.1796   0.1967   0.2274 e  0.3110 e
2     ...   0.1061    0.1042    0.1041   0.1018    0.1205    0.1150
3     ...   0.1821    0.1888    0.2159   0.2834    0.3551    0.3130
4     ...   0.1150    0.1222    0.1853   0.2165    0.2431    0.1989
...   ...       ...       ...       ...      ...       ...       ...
2881  ...        :         :    0.1515   0.1652    0.1860    0.2262
2882  ...   0.0464    0.0501    0.0733   0.0830    0.1177    0.0861
2883  ...        :         :    0.1222   0.1794    0.2261    0.2513
2884  ...        :         :    0.1771   0.2671    0.3160    0.3330
2885  ...        :         :    0.1970   0.4417    0.4725    0.3620

      2023-S2   2024-S1   2024-S2   2025-S1
0     0.1468 e   0.1503   0.1551 e   0.1703
1     0.3163 e  0.2791 e  0.2693 e  0.2785 e
2      0.1147    0.1173    0.1207    0.1448
3      0.2875    0.2507    0.2560    0.2800
4      0.1759    0.1500    0.1699    0.1667
...        ...       ...       ...       ...
2881   0.2301    0.2317    0.2098    0.2160
2882   0.0721    0.0741    0.0670    0.0716
2883   0.2406    0.1929         :         :
2884   0.3090    0.2256    0.2511         :
2885   0.3564    0.2485    0.1736    0.1801

[2886 rows x 38 columns]

In [8]:
enrg_cst_split = enrg_cst[r'freq,product,nrg_cons,unit,tax,currency,geo\TIME_PERIOD'].str.split(',', expand=True)
enrg_cst = pd.concat([enrg_cst, enrg_cst_split], axis=1)
enrg_cst.rename(columns={0: 'freq', 1: 'product', 2: 'nrg_cons',  3: 'unit', 4: 'tax', 5: 'currency', 6:'geo_TIME_PERIOD'}, inplace=True)
enrg_cst = enrg_cst.drop(r'freq,product,nrg_cons,unit,tax,currency,geo\TIME_PERIOD', axis=1)
enrg_cst.rename(columns={"geo_TIME_PERIOD": "geo"}, inplace=True)
enrg_cst.columns = enrg_cst.columns.str.strip()
enrg_cst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2886 entries, 0 to 2885
Data columns (total 44 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   2007-S1   2886 non-null   object
 1   2007-S2   2886 non-null   object
 2   2008-S1   2886 non-null   object
 3   2008-S2   2886 non-null   object
 4   2009-S1   2886 non-null   object
 5   2009-S2   2886 non-null   object
 6   2010-S1   2886 non-null   object
 7   2010-S2   2886 non-null   object
 8   2011-S1   2886 non-null   object
 9   2011-S2   2886 non-null   object
 10  2012-S1   2886 non-null   object
 11  2012-S2   2886 non-null   object
 12  2013-S1   2886 non-null   object
 13  2013-S2   2886 non-null   object
 14  2014-S1   2886 non-null   object
 15  2014-S2   2886 non-null   object
 16  2015-S1   2886 non-null   object
 17  2015-S2   2886 non-null   object
 18  2016-S1   2886 non-null   object
 19  2016-S2   2886 non-null   object
 20  2017-S1   2886 non-null   object
 21  2017-S2   2886 non-null   object
 22  2018-S1   2886 non-null   object
 23  2018-S2   2886 non-null   object
 24  2019-S1   2886 non-null   object
 25  2019-S2   2886 non-null   object
 26  2020-S1   2886 non-null   object
 27  2020-S2   2886 non-null   object
 28  2021-S1   2886 non-null   object
 29  2021-S2   2886 non-null   object
 30  2022-S1   2886 non-null   object
 31  2022-S2   2886 non-null   object
 32  2023-S1   2886 non-null   object
 33  2023-S2   2886 non-null   object
 34  2024-S1   2886 non-null   object
 35  2024-S2   2886 non-null   object
 36  2025-S1   2886 non-null   object
 37  freq      2886 non-null   object
 38  product   2886 non-null   object
 39  nrg_cons  2886 non-null   object
 40  unit      2886 non-null   object
 41  tax       2886 non-null   object
 42  currency  2886 non-null   object
 43  geo       2886 non-null   object
dtypes: object(44)
memory usage: 992.2+ KB

In [9]:
years_take = ['2016-S1', '2016-S2', '2020-S1', '2020-S2']

data_temp  = enrg_cst.copy()

pattern = re.compile(r'^\s*(\d+(?:\.\d+)?)?\s*[: ]*\s*([A-Za-z]+)?\s*$')

for year in years_take:
    column_series = data_temp[year].astype(str).str.strip() 

    extracted_df = column_series.str.extract(pattern, expand=True)
    # print(extracted_df)

    num_col_name = f'num_{year}'
    data_temp[num_col_name] = pd.to_numeric(extracted_df[0], errors='coerce') 
    # print(ain2[num_col_name])
    
    flag_col_name = f'flag_{year}'
    data_temp[flag_col_name] = extracted_df[1].fillna('NaN') 
    # print(ain2[flag_col_name])
    # print('#########################')
# Display the resulting DataFrame
enrg_cst_new = data_temp
print(enrg_cst_new)

     2007-S1  2007-S2  2008-S1  2008-S2  2009-S1  2009-S2  2010-S1  2010-S2  \
0         :        :        :        :        :        :        :        :
1         :   0.1412   0.1476    0.144   0.1601   0.1588   0.1545   0.1547
2         :        :        :        :        :        :        :        :
3         :   0.1435   0.1706   0.1728   0.1605   0.1547   0.1562   0.1584
4         :   0.0767   0.0767   0.0874   0.0879   0.0864   0.0854   0.0851
...      ...      ...      ...      ...      ...      ...      ...      ...
2881      :        :        :        :        :        :        :        :
2882      :        :        :        :        :        :        :        :
2883      :        :        :        :        :        :        :        :
2884      :        :        :        :        :        :        :        :
2885      :        :        :        :        :        :        :        :

      2011-S1  2011-S2  ... currency geo num_2016-S1 flag_2016-S1 num_2016-S2  \
0          :        :   ...      EUR  AL         NaN          NaN         NaN
1     0.1547   0.1555   ...      EUR  AT      0.1519          NaN      0.1490
2          :        :   ...      EUR  BA      0.1003          NaN      0.1005
3     0.1721   0.1743   ...      EUR  BE      0.1803          NaN      0.1895
4     0.0864   0.0929   ...      EUR  BG      0.1285          NaN      0.1136
...       ...      ...  ...      ...  ..         ...          ...         ...
2881       :        :   ...      PPS  RS         NaN          NaN         NaN
2882       :        :   ...      PPS  SE         NaN          NaN         NaN
2883       :        :   ...      PPS  SI         NaN          NaN         NaN
2884       :        :   ...      PPS  SK         NaN          NaN         NaN
2885       :        :   ...      PPS  TR         NaN          NaN         NaN

     flag_2016-S2 num_2020-S1 flag_2020-S1 num_2020-S2 flag_2020-S2
0             NaN      0.1245            e      0.1243            e
1             NaN      0.1614          NaN      0.1624          NaN
2             NaN      0.1061          NaN      0.1061          NaN
3             NaN      0.1872          NaN      0.1821          NaN
4             NaN      0.1117          NaN      0.1150          NaN
...           ...         ...          ...         ...          ...
2881          NaN         NaN          NaN         NaN          NaN
2882          NaN      0.0421          NaN      0.0464          NaN
2883          NaN         NaN          NaN         NaN          NaN
2884          NaN         NaN          NaN         NaN          NaN
2885          NaN         NaN          NaN         NaN          NaN

[2886 rows x 52 columns]

In [10]:
start_year = 2005
end_year = 2025
seasons = ['S1', 'S2']

years_to_drop = []
for y in range(start_year, end_year + 1):
    for s in seasons:
        years_to_drop.append(f'{y}-{s}')

existing_cols_to_drop = [col for col in years_to_drop if col in enrg_cst_new.columns]
enrg_cst_new.drop(existing_cols_to_drop, axis='columns', inplace=True)
enrg_cst_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2886 entries, 0 to 2885
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   freq          2886 non-null   object
 1   product       2886 non-null   object
 2   nrg_cons      2886 non-null   object
 3   unit          2886 non-null   object
 4   tax           2886 non-null   object
 5   currency      2886 non-null   object
 6   geo           2886 non-null   object
 7   num_2016-S1   2115 non-null   float64
 8   flag_2016-S1  2886 non-null   object
 9   num_2016-S2   2106 non-null   float64
 10  flag_2016-S2  2886 non-null   object
 11  num_2020-S1   2358 non-null   float64
 12  flag_2020-S1  2886 non-null   object
 13  num_2020-S2   2304 non-null   float64
 14  flag_2020-S2  2886 non-null   object
dtypes: float64(4), object(11)
memory usage: 338.3+ KB

In [11]:
enrg_cst_new['2016'] = (enrg_cst_new['num_2016-S1'] + enrg_cst_new['num_2016-S2'])/2
enrg_cst_new['2020'] = (enrg_cst_new['num_2020-S1'] + enrg_cst_new['num_2020-S2'])/2
print(enrg_cst_new)

     freq product   nrg_cons unit    tax currency geo  num_2016-S1  \
0       S    6000  MWH20-499  KWH  I_TAX      EUR  AL          NaN
1       S    6000  MWH20-499  KWH  I_TAX      EUR  AT       0.1519
2       S    6000  MWH20-499  KWH  I_TAX      EUR  BA       0.1003
3       S    6000  MWH20-499  KWH  I_TAX      EUR  BE       0.1803
4       S    6000  MWH20-499  KWH  I_TAX      EUR  BG       0.1285
...   ...     ...        ...  ...    ...      ...  ..          ...
2881    S    6000    TOT_KWH  KWH  X_VAT      PPS  RS          NaN
2882    S    6000    TOT_KWH  KWH  X_VAT      PPS  SE          NaN
2883    S    6000    TOT_KWH  KWH  X_VAT      PPS  SI          NaN
2884    S    6000    TOT_KWH  KWH  X_VAT      PPS  SK          NaN
2885    S    6000    TOT_KWH  KWH  X_VAT      PPS  TR          NaN

     flag_2016-S1  num_2016-S2 flag_2016-S2  num_2020-S1 flag_2020-S1  \
0             NaN          NaN          NaN       0.1245            e
1             NaN       0.1490          NaN       0.1614          NaN
2             NaN       0.1005          NaN       0.1061          NaN
3             NaN       0.1895          NaN       0.1872          NaN
4             NaN       0.1136          NaN       0.1117          NaN
...           ...          ...          ...          ...          ...
2881          NaN          NaN          NaN          NaN          NaN
2882          NaN          NaN          NaN       0.0421          NaN
2883          NaN          NaN          NaN          NaN          NaN
2884          NaN          NaN          NaN          NaN          NaN
2885          NaN          NaN          NaN          NaN          NaN

      num_2020-S2 flag_2020-S2     2016     2020
0          0.1243            e      NaN  0.12440
1          0.1624          NaN  0.15045  0.16190
2          0.1061          NaN  0.10040  0.10610
3          0.1821          NaN  0.18490  0.18465
4          0.1150          NaN  0.12105  0.11335
...           ...          ...      ...      ...
2881          NaN          NaN      NaN      NaN
2882       0.0464          NaN      NaN  0.04425
2883          NaN          NaN      NaN      NaN
2884          NaN          NaN      NaN      NaN
2885          NaN          NaN      NaN      NaN

[2886 rows x 17 columns]

In [12]:
import numpy as np

enrg_cst_new['flag_2016'] = np.where(
    enrg_cst_new['flag_2016-S2'].notna(), 
    enrg_cst_new['flag_2016-S2'], 
    enrg_cst_new['flag_2016-S1']
)

enrg_cst_new['flag_2020'] = np.where(
    enrg_cst_new['flag_2020-S2'].notna(), 
    enrg_cst_new['flag_2020-S2'], 
    enrg_cst_new['flag_2020-S1']
)

print(enrg_cst_new)

     freq product   nrg_cons unit    tax currency geo  num_2016-S1  \
0       S    6000  MWH20-499  KWH  I_TAX      EUR  AL          NaN
1       S    6000  MWH20-499  KWH  I_TAX      EUR  AT       0.1519
2       S    6000  MWH20-499  KWH  I_TAX      EUR  BA       0.1003
3       S    6000  MWH20-499  KWH  I_TAX      EUR  BE       0.1803
4       S    6000  MWH20-499  KWH  I_TAX      EUR  BG       0.1285
...   ...     ...        ...  ...    ...      ...  ..          ...
2881    S    6000    TOT_KWH  KWH  X_VAT      PPS  RS          NaN
2882    S    6000    TOT_KWH  KWH  X_VAT      PPS  SE          NaN
2883    S    6000    TOT_KWH  KWH  X_VAT      PPS  SI          NaN
2884    S    6000    TOT_KWH  KWH  X_VAT      PPS  SK          NaN
2885    S    6000    TOT_KWH  KWH  X_VAT      PPS  TR          NaN

     flag_2016-S1  num_2016-S2 flag_2016-S2  num_2020-S1 flag_2020-S1  \
0             NaN          NaN          NaN       0.1245            e
1             NaN       0.1490          NaN       0.1614          NaN
2             NaN       0.1005          NaN       0.1061          NaN
3             NaN       0.1895          NaN       0.1872          NaN
4             NaN       0.1136          NaN       0.1117          NaN
...           ...          ...          ...          ...          ...
2881          NaN          NaN          NaN          NaN          NaN
2882          NaN          NaN          NaN       0.0421          NaN
2883          NaN          NaN          NaN          NaN          NaN
2884          NaN          NaN          NaN          NaN          NaN
2885          NaN          NaN          NaN          NaN          NaN

      num_2020-S2 flag_2020-S2     2016     2020 flag_2016 flag_2020
0          0.1243            e      NaN  0.12440       NaN         e
1          0.1624          NaN  0.15045  0.16190       NaN       NaN
2          0.1061          NaN  0.10040  0.10610       NaN       NaN
3          0.1821          NaN  0.18490  0.18465       NaN       NaN
4          0.1150          NaN  0.12105  0.11335       NaN       NaN
...           ...          ...      ...      ...       ...       ...
2881          NaN          NaN      NaN      NaN       NaN       NaN
2882       0.0464          NaN      NaN  0.04425       NaN       NaN
2883          NaN          NaN      NaN      NaN       NaN       NaN
2884          NaN          NaN      NaN      NaN       NaN       NaN
2885          NaN          NaN      NaN      NaN       NaN       NaN

[2886 rows x 19 columns]

In [ ]:
enrg_cst_new = enrg_cst_new.drop(columns=['flag_2016-S1', 'flag_2016-S2', 'flag_2020-S1', 'flag_2020-S2', 'num_2016-S1', 'num_2016-S2', 'num_2020-S1', 'num_2020-S2'])

print(enrg_cst_new)

     freq product   nrg_cons unit    tax currency geo     2016     2020  \
0       S    6000  MWH20-499  KWH  I_TAX      EUR  AL      NaN  0.12440
1       S    6000  MWH20-499  KWH  I_TAX      EUR  AT  0.15045  0.16190
2       S    6000  MWH20-499  KWH  I_TAX      EUR  BA  0.10040  0.10610
3       S    6000  MWH20-499  KWH  I_TAX      EUR  BE  0.18490  0.18465
4       S    6000  MWH20-499  KWH  I_TAX      EUR  BG  0.12105  0.11335
...   ...     ...        ...  ...    ...      ...  ..      ...      ...
2881    S    6000    TOT_KWH  KWH  X_VAT      PPS  RS      NaN      NaN
2882    S    6000    TOT_KWH  KWH  X_VAT      PPS  SE      NaN  0.04425
2883    S    6000    TOT_KWH  KWH  X_VAT      PPS  SI      NaN      NaN
2884    S    6000    TOT_KWH  KWH  X_VAT      PPS  SK      NaN      NaN
2885    S    6000    TOT_KWH  KWH  X_VAT      PPS  TR      NaN      NaN

     flag_2016 flag_2020
0          NaN         e
1          NaN       NaN
2          NaN       NaN
3          NaN       NaN
4          NaN       NaN
...        ...       ...
2881       NaN       NaN
2882       NaN       NaN
2883       NaN       NaN
2884       NaN       NaN
2885       NaN       NaN

[2886 rows x 11 columns]

In [17]:
enrg_cst_new.to_csv('enrg_cst.csv', index = False)

### Human capital 

is the proportion of employees that have a tertiary education.

In [22]:
path = 'C:/Users/ydmar/Documents/UW/Master thesis/Step 1 - meeting 18.10/data - september/'

hum_cap = pd.read_csv(path + 'estat_edat_lfs_9910.tsv/estat_edat_lfs_9910.tsv', sep='\t')
print(hum_cap)

       freq,unit,nace_r2,isced11,age,sex,geo\TIME_PERIOD 2008  2009     2010   \
0                               A,PC,A,ED0-2,Y15-24,F,AT   : u   : u      : u
1                               A,PC,A,ED0-2,Y15-24,F,BA    :     :        :
2                               A,PC,A,ED0-2,Y15-24,F,BE  : bu   : u      : u
3                               A,PC,A,ED0-2,Y15-24,F,BG   : u   : u     : bu
4                               A,PC,A,ED0-2,Y15-24,F,CH   : u   : u  68.1 bu
...                                                  ...   ...   ...      ...
241725                          A,PC,U,ED5-8,Y55-74,T,SE   : u   : u      : u
241726                          A,PC,U,ED5-8,Y55-74,T,SI    :     :        :
241727                          A,PC,U,ED5-8,Y55-74,T,SK   : u    :        :
241728                          A,PC,U,ED5-8,Y55-74,T,TR    :    : u      : u
241729                          A,PC,U,ED5-8,Y55-74,T,UK  : bu   : u     : bu

         2011    2012    2013     2014    2015    2016    2017    2018  2019   \
0          : u     : u     : u     : bu     : u     : u     : u     : u   : u
1           :       :       :        :       :       :       :       :     :
2          : u     : u     : u     : bu     : u     : u    : bu     : u   : u
3         : bu     : u     : u     : bu     : u     : u     : u     : u  : bu
4       60.4 u  46.9 u  58.9 u  61.0 bu  36.8 u  33.1 u  34.5 u  49.4 u   : u
...        ...     ...     ...      ...     ...     ...     ...     ...   ...
241725     : u     : u     : u     : bu     : u     : u     : u    : bu   : u
241726      :       :       :        :       :       :       :       :    : u
241727    : bu     : u      :      : bu     : u     : u     : u     : u    :
241728  72.4 u  74.7 u  36.0 u       :      : u     : u     : u     : u   : u
241729    : bu     : u     : u     : bu     : u     : u     : u  42.9 u   : u

       2020  2021  2022  2023  2024
0        : u  : bu   : u   : u   : u
1         :    : u   : u    :    : u
2        : u  : bu   : u   : u   : u
3        : u  : bu   : u   : u  : bu
4        : u  : bu   : u   : u   : u
...      ...   ...   ...   ...   ...
241725   : u  : bu   : u   : u    :
241726    :   : bu   : u  : bu   : u
241727    :   : bu   : u   : u    :
241728   : u  : bu   : u    :    : u
241729    :     :     :     :     :

[241730 rows x 18 columns]

In [23]:
hum_cap_split = hum_cap[r'freq,unit,nace_r2,isced11,age,sex,geo\TIME_PERIOD'].str.split(',', expand=True)
hum_cap = pd.concat([hum_cap, hum_cap_split], axis=1)
hum_cap.rename(columns={0: 'freq', 1: 'unit', 2: 'nace_r2',  3: 'isced11', 4: 'age', 5 : 'sex', 6 : 'geo\TIME_PERIOD'}, inplace=True)
hum_cap  = hum_cap.drop(r'freq,unit,nace_r2,isced11,age,sex,geo\TIME_PERIOD', axis=1)
hum_cap.rename(columns={"geo_TIME_PERIOD": "geo"}, inplace=True)
hum_cap.columns = hum_cap.columns.str.strip()
hum_cap.info()

<>:3: SyntaxWarning: invalid escape sequence '\T'
<>:3: SyntaxWarning: invalid escape sequence '\T'
C:\Users\ydmar\AppData\Local\Temp\ipykernel_20564\889841396.py:3: SyntaxWarning: invalid escape sequence '\T'
  hum_cap.rename(columns={0: 'freq', 1: 'unit', 2: 'nace_r2',  3: 'isced11', 4: 'age', 5 : 'sex', 6 : 'geo\TIME_PERIOD'}, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241730 entries, 0 to 241729
Data columns (total 24 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   2008             241730 non-null  object
 1   2009             241730 non-null  object
 2   2010             241730 non-null  object
 3   2011             241730 non-null  object
 4   2012             241730 non-null  object
 5   2013             241730 non-null  object
 6   2014             241730 non-null  object
 7   2015             241730 non-null  object
 8   2016             241730 non-null  object
 9   2017             241730 non-null  object
 10  2018             241730 non-null  object
 11  2019             241730 non-null  object
 12  2020             241730 non-null  object
 13  2021             241730 non-null  object
 14  2022             241730 non-null  object
 15  2023             241730 non-null  object
 16  2024             241730 non-null  object
 17  freq             241730 non-null  object
 18  unit             241730 non-null  object
 19  nace_r2          241730 non-null  object
 20  isced11          241730 non-null  object
 21  age              241730 non-null  object
 22  sex              241730 non-null  object
 23  geo\TIME_PERIOD  241730 non-null  object
dtypes: object(24)
memory usage: 44.3+ MB

In [24]:
years_take = ['2016', '2020']
data_temp  = hum_cap.copy()

pattern = re.compile(r'^\s*(\d+(?:\.\d+)?)?\s*[: ]*\s*([A-Za-z]+)?\s*$')

for year in years_take:
    column_series = data_temp[year].astype(str).str.strip() 

    extracted_df = column_series.str.extract(pattern, expand=True)
    # print(extracted_df)

    num_col_name = f'num_{year}'
    data_temp[num_col_name] = pd.to_numeric(extracted_df[0], errors='coerce') 
    # print(ain2[num_col_name])
    
    flag_col_name = f'flag_{year}'
    data_temp[flag_col_name] = extracted_df[1].fillna('NaN') 
    # print(ain2[flag_col_name])
    # print('#########################')
# Display the resulting DataFrame
hum_cap_new = data_temp
print(hum_cap_new)

        2008 2009     2010    2011    2012    2013     2014    2015    2016  \
0        : u  : u      : u     : u     : u     : u     : bu     : u     : u
1         :    :        :       :       :       :        :       :       :
2       : bu  : u      : u     : u     : u     : u     : bu     : u     : u
3        : u  : u     : bu    : bu     : u     : u     : bu     : u     : u
4        : u  : u  68.1 bu  60.4 u  46.9 u  58.9 u  61.0 bu  36.8 u  33.1 u
...      ...  ...      ...     ...     ...     ...      ...     ...     ...
241725   : u  : u      : u     : u     : u     : u     : bu     : u     : u
241726    :    :        :       :       :       :        :       :       :
241727   : u   :        :     : bu     : u      :      : bu     : u     : u
241728    :   : u      : u  72.4 u  74.7 u  36.0 u       :      : u     : u
241729  : bu  : u     : bu    : bu     : u     : u     : bu     : u     : u

          2017  ... unit nace_r2 isced11     age sex geo\TIME_PERIOD num_2016  \
0          : u  ...   PC       A   ED0-2  Y15-24   F              AT      NaN
1           :   ...   PC       A   ED0-2  Y15-24   F              BA      NaN
2         : bu  ...   PC       A   ED0-2  Y15-24   F              BE      NaN
3          : u  ...   PC       A   ED0-2  Y15-24   F              BG      NaN
4       34.5 u  ...   PC       A   ED0-2  Y15-24   F              CH     33.1
...        ...  ...  ...     ...     ...     ...  ..             ...      ...
241725     : u  ...   PC       U   ED5-8  Y55-74   T              SE      NaN
241726      :   ...   PC       U   ED5-8  Y55-74   T              SI      NaN
241727     : u  ...   PC       U   ED5-8  Y55-74   T              SK      NaN
241728     : u  ...   PC       U   ED5-8  Y55-74   T              TR      NaN
241729     : u  ...   PC       U   ED5-8  Y55-74   T              UK      NaN

       flag_2016 num_2020 flag_2020
0              u      NaN         u
1            NaN      NaN       NaN
2              u      NaN         u
3              u      NaN         u
4              u      NaN         u
...          ...      ...       ...
241725         u      NaN         u
241726       NaN      NaN       NaN
241727         u      NaN       NaN
241728         u      NaN         u
241729         u      NaN       NaN

[241730 rows x 28 columns]

In [25]:
y = 2008
while y <= 2024:
    column_to_drop = str(y)
    hum_cap_new.drop([column_to_drop], axis='columns', inplace=True)
    y += 1
hum_cap_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241730 entries, 0 to 241729
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   freq             241730 non-null  object
 1   unit             241730 non-null  object
 2   nace_r2          241730 non-null  object
 3   isced11          241730 non-null  object
 4   age              241730 non-null  object
 5   sex              241730 non-null  object
 6   geo\TIME_PERIOD  241730 non-null  object
 7   num_2016         124626 non-null  float64
 8   flag_2016        241730 non-null  object
 9   num_2020         114497 non-null  float64
 10  flag_2020        241730 non-null  object
dtypes: float64(2), object(9)
memory usage: 20.3+ MB

In [26]:
hum_cap_new.to_csv('human_capital.csv')